### ISSUE TITLE
QuantopianUSFuturesCalendar default start time is 2000-01-01 - is this still an issue?

### ISSUE THREAD

**Issue by RichardDale** [gerrymanoim/exchange_calendars#112]
Within us_futures_calendar.py, the class QuantopianUSFuturesCalendar has a property of default_start returning a Teimstamp dated 2000-01-01, with the comment:
        # XXX: Override the default start date. This is a stopgap for memory
        # issues caused by upgrading to pandas 18. This calendar is the most
        # severely affected since it has the most total minutes of any of the
        # zipline calendars.

This is seemingly referencing Pandas 0.18, which was released in 2016, and of course, we're many releases since there.

As exchange-calendars is used by Zipline (Reloaded), this prevents users from backtesting on futures prior to this date, requiring manual patching by the user to extend prior to this.

I'm only working with daily data and there's no noticeble particular issue with that periodicity as far as RAM is concerned, but I'm unable to say whether this is still a problem for other periodicities (such as minutes).

Given we're now 5 yeras later, could this default be extended to, say, 1970-01-01 (or earlier).

The other exchange calendars (such as NYSE) seem to default to the earliest holiday definition.  For example, NYSE goes back to 1848 so is probably a non-issue regarding RAM for futures....

**Comment by maread99** [comment]
Hi @RichardDale, the default on this calendar should actually be the same as most of the rest, which is 'twenty years prior to today'...

```python
import exchange_calendars as xcals
>>> cal = xcals.get_calendar("XLON")
>>> cal.first_session
Timestamp('2001-11-05 00:00:00+0000', tz='UTC', freq='C')
```

To start a calendar earlier that the default just pass `start`:
```python
>>> cal = xcals.get_calendar("us_futures", "1990-01-01")
>>> cal.first_session
Timestamp('1990-01-02 00:00:00+0000', tz='UTC', freq='C')

>>> cal = xcals.get_calendar("us_futures", start="1995-03-20", side="right")
>>> cal.first_minute
Timestamp('1995-03-19 23:01:00+0000', tz='UTC')
```

The same kwargs can be passed directly to `QuantopianUSFuturesCalendar`.

**Comment by RichardDale** [comment]
Thanks Marcus - very helpful - as it turns out, the date is "defaulted" by Zipline (v2.2 and below) under its data/bundles/core.py wihtin its ingest function where it calls get_calendar with only an exchange parameter, then realigns the start_session to the first session in the calendar. 

I'll submit a patch/PR to the Zipline (Reloaded) v2.2 to make use of  start_session that is passed in to correctly the calendar used for the rest of the Zipline ingest routines.

Cheers,
Richard.
