### ISSUE TITLE
End of calendar reached for XETR and XFRA

### ISSUE THREAD

**Issue by hannes101** [gerrymanoim/exchange_calendars#126]
Sorry, if this might be a stupid question, since I don't know how the calendars are implemented. However, when trying to check the trading days for the next year 2022, I ran into an error, with the defined end being later than the last available calendar date.
Please see the following code example, which triggers the error:

```
import exchange_calendars as ecal
cal_FRA = ecal.get_calendar("XFRA")
cal_XETR = ecal.get_calendar("XETR")

start, end = "2022-01-01", "2022-12-31"
df_trading_days_xetra =  pd.DataFrame((cal_XETR.trading_index(start, end, "24h", intervals=False)), columns=['Dates'])
print(df_trading_days_xetra)
```
This results in the following error

`Traceback (most recent call last):
  File "R:\Zentrale\ZB-S\Daten\S5\S52\AD\JL\python\python_eikon\join_test.py", line 63, in <module>
    df_trading_days_xetra =  pd.DataFrame((cal_XETR.trading_index(start, end, "24h", intervals=False)), columns=['Dates'])
  File "C:\Workspace\Python_Runtime\Envs\python_eikon\lib\site-packages\exchange_calendars\exchange_calendar.py", line 2347, in trading_index
    start, end = self._parse_start_end_dates(start, end, parse)
  File "C:\Workspace\Python_Runtime\Envs\python_eikon\lib\site-packages\exchange_calendars\exchange_calendar.py", line 1980, in _parse_start_end_dates
    return parse_date(start, "start", self), parse_date(end, "end", self)
  File "C:\Workspace\Python_Runtime\Envs\python_eikon\lib\site-packages\exchange_calendars\calendar_helpers.py", line 323, in parse_date
    raise errors.DateOutOfBounds(calendar, ts, param_name)
exchange_calendars.errors.DateOutOfBounds: Parameter `end` receieved as '2022-12-31 00:00:00+00:00' although cannot be later than the last session of calendar 'XETR' ('2022-12-29 00:00:00+00:00').`

When changing the start date to days before 2022-12-28, the dataframe gets created without any issue.

**Comment by maread99** [comment]
Hi @hannes101.

By default, a calendar ends one year ahead of the current date. The trading index method has raised the error as `end` was passed as a date that's later than the calendar's last session (2022-12-29).

Just pass `get_calendar`'s optional `end` parameter to define the calendar end as a session that's no earlier than the last date that you want to the index to cover. For example...

```python
import exchange_calendars as xcals
cal = xcals.get_calendar("XETR", end="2023-01-15")  # for example
start, end = "2022-01-01", "2022-12-31"
index = cal.trading_index(start, end, "24h", intervals=False)
```

**Comment by hannes101** [comment]
Thanks a lot for the quick response!
