### ISSUE TITLE
Quantopian US Futures Calendar last session is  '2023-01-03 00:00:00+00:00'

### ISSUE THREAD

**Issue by chicago-joe** [gerrymanoim/exchange_calendars#129]
Is there another way I can implement a futures calendar? I'm trying to pull the next 6 months of monthly contract expirations

**Comment by maread99** [comment]
Hi @chicago-joe.

The last session can be changed to any date by passing the optional `end` parameter to the calendar constructor or via `get_calendar`. There's an example on #126.

Would that solve your issue?

**Comment by chicago-joe** [comment]
@maread99 unfortunately not, I think the Quantopian (now extinct as a firm) only dated the US Futures calendar through the year 2022. If you pull `all_sessions`, you'll see the last session of the whole set is 2023-01-03

**Comment by maread99** [comment]
```python
> import exchange_calendars as xcals
> cal = xcals.get_calendar("us_futures", end="2027-12-31")
> cal.sessions[-3:]

DatetimeIndex(['2027-12-29 00:00:00+00:00', '2027-12-30 00:00:00+00:00',
               '2027-12-31 00:00:00+00:00'],
              dtype='datetime64[ns, UTC]', freq='C')
```

You can set the `end` date to whenever you want the calendar to run to (if it's not passed it'll default to a year ahead of 'today'),
