### ISSUE TITLE
while using XBOM.IS_SESSION getting DateOutOfBounds error:

### ISSUE THREAD

**Issue by srinivasakumar-a** [gerrymanoim/exchange_calendars#130]
Exchange_Calendars package was working good until 31/12/2021 and after that receiving the `DateOutOfBounds` error during `xbom.is_session` method. I have updated the package to 3.5 and did check the code yesterday to see XBOM.py file was missing the 2022 calendar entries and at the same time there was a PR pending with changes to be merged with main branch. Today, I see that the changes are merged with main branch. However, I still get the error. 

Attaching the screenshot of error.
![Screenshot 2022-01-04 150539](https://user-images.githubusercontent.com/33969314/148043097-7496a60c-5a23-458b-b0c3-be23a5cd34bd.png)

**Comment by maread99** [comment]
Hi @srinivasakumar-a, these changes won't be relfected in PyPI until the next release is cut.

In the meantime you could always try installing the package directly from the main branch of the github repo, something like this should work...
`$ pip install git+https://github.com/gerrymanoim/exchange_calendars.git#egg=exchange_calendars`

**Comment by srinivasakumar-a** [comment]
> Hi @srinivasakumar-a, these changes won't be relfected in PyPI until the next release is cut.
> 
> In the meantime you could always try installing the package directly from the main branch of the github repo, something like this should work... `$ pip install git+https://github.com/gerrymanoim/exchange_calendars.git#egg=exchange_calendars`
> 
> Reference: [installing packages from git](https://pip.pypa.io/en/latest/topics/vcs-support/#git)

installing from github main branch directly helped to resolve my issue! 
Thanks a lot! 
HAPPY NEW YEAR 2022 :)
