### ISSUE TITLE
get_calendar 20yr default override

### ISSUE THREAD

**Issue by ktrosper** [gerrymanoim/exchange_calendars#134]
Hi there,
I'm cleaning up a 20yr + data set before attempting my zipline backtesting and I'm calling the following example to get valid trade days:
start = '2000-01-13'
end = '2022-01-13'
nys = xcals.get_calendar("XNYS")  # New York Stock Exchange
caldatelist = nys.sessions_in_range(start, end) #valid trading days list
caldatelist

return:
DateOutOfBounds: Parameter `start` receieved as '2000-01-13 00:00:00+00:00' although cannot be earlier than the first session of calendar 'XNYS' ('2002-01-15 00:00:00+00:00').

It seems that passing the start value isn't overriding the 20yr default as suggested here in a similar issue:
https://github.com/gerrymanoim/exchange_calendars/issues/112

Thank you.

**Comment by maread99** [comment]
Hi @ktrosper.

The calendar needs to cover the period that you are requesting sessions for. The `start` option can be passed to `get_calendar` (or directly to a calendar class) to define an earlier calendar start date than the default. Something like:

```python
cal_start = '2000-01-01'
start = '2000-01-13'
end = '2022-01-13'
nys = xcals.get_calendar("XNYS", start=cal_start) # New York Stock Exchange
caldatelist = nys.sessions_in_range(start, end)
```

**Comment by ktrosper** [comment]
thanks much! That did the trick.
re: docs
https://github.com/gerrymanoim/exchange_calendars/blob/bc313f768871f032573f7de894f6859bd5ab81bd/docs/tutorials/calendar_methods.ipynb

Methods that query a range of dates (link doesn't take you to the range of dates section)
Also:
cal_start param isn't mentioned in that section

Thank you again!

**Comment by maread99** [comment]
The links will only work if viewed in Jupyter Lab / Notebook or in the nbviewer.

Questions concerning the `start` option have come up a few times. I've added to include a clearer explanation to the TODO (#61) for the next major release.

Thanks.
