### ISSUE TITLE
Update BVMF holidays to account for 2022's changes

### ISSUE THREAD

**Issue by almeidaxan** [gerrymanoim/exchange_calendars#136]
Starting in 2022, B3 will operate normally on municipal and state holidays, namely [Aniversário de São Paulo](https://github.com/gerrymanoim/exchange_calendars/blob/4e60ce2c4a064ba070774f73d699f4a628b580db/exchange_calendars/exchange_calendar_bvmf.py#L38-L42), [Revolução Constitucionalista](https://github.com/gerrymanoim/exchange_calendars/blob/4e60ce2c4a064ba070774f73d699f4a628b580db/exchange_calendars/exchange_calendar_bvmf.py#L75-L77), and [Consciência Negra](https://github.com/gerrymanoim/exchange_calendars/blob/4e60ce2c4a064ba070774f73d699f4a628b580db/exchange_calendars/exchange_calendar_bvmf.py#L103-L105).

Here's a circular letter issued by B3 on 2020 anticipating some of these changes:
- https://www.b3.com.br/data/files/55/37/81/D0/038D5710700BFA57AC094EA8/OC%20150-2020%20PRE%20-%20%202021_2022%20Calendar_Public%20Holidays_ING.pdf (see Section 2.2).

And here are some external sources (only in portuguese, sorry):

- https://www.infomoney.com.br/mercados/bolsa-divulga-calendario-e-informa-que-tera-pregao-em-feriados-municipais-de-sp-a-partir-de-2022-veja-as-datas/
- https://economia.uol.com.br/noticias/estadao-conteudo/2020/11/18/b3-tera-pregao-em-feriados-municipais-de-sp-a-partir-de-2022.htm
- https://guru.com.vc/noticias/feriado-de-25-de-janeiro-b3-vai-abrir-vai-funcionar-o-pregao/
- https://www.spacemoney.com.br/geral/b3-funcionara-normalmente-no-aniversario-da-cidade-de-sao-paulo/176793/

I believe it can be fixed easily by adding the `end_date` parameter to each of the aforementioned holiday instances.
Since this seems like a good first issue, I could tackle it as my first contribution.

**Comment by pbabics** [comment]
@almeidaxan I've fixed the holiday for [Aniversário de São Paulo](https://github.com/gerrymanoim/exchange_calendars/blob/4e60ce2c4a064ba070774f73d699f4a628b580db/exchange_calendars/exchange_calendar_bvmf.py#L38-L42) in !162

As you mentioned it is enough to add `end_date` and then regenerate the csv files used for testing via 

```bash
python etc/make_exchange_calendar_test_csv.py BVMF
```

**Comment by almeidaxan** [comment]
This issue was only partially implemented - it is still necessary to update two more holidays: Revolução Constitucionalista and Consciência Negra.

@gerrymanoim Could you please reopen it?

**Comment by gerrymanoim** [comment]
Apologies - reopened!

**Comment by almeidaxan** [comment]
No worries - I'll try to work on it later today.
