### ISSUE TITLE
XSES calendar ends at 2021-12-31

### ISSUE THREAD

**Issue by npezolano** [gerrymanoim/exchange_calendars#143]
```
import exchange_calendars as xcals
import pandas as pd

xses = xcals.get_calendar("XSES")

xses.is_session(pd.Timestamp("2022-01-01"))
```
---------------------------------------------------------------------------
DateOutOfBounds                           Traceback (most recent call last)
<ipython-input-9-277333fbb282> in <module>
----> 1 xses.is_session(pd.Timestamp("2022-01-01"))

~/anaconda3/lib/python3.7/site-packages/exchange_calendars/exchange_calendar.py in is_session(self, dt, _parse)
   1141         """
   1142         if _parse:
-> 1143             dt = parse_date(dt, "dt", self)
   1144         idx = self._get_date_idx(dt, _parse=False)
   1145         return bool(self.sessions_nanos[idx] == dt.value)  # convert from np.bool_

~/anaconda3/lib/python3.7/site-packages/exchange_calendars/calendar_helpers.py in parse_date(date, param_name, calendar, raise_oob)
    317             raise ValueError("`calendar` must be passed if `raise_oob` is True.")
    318         if calendar._date_oob(ts):
--> 319             raise errors.DateOutOfBounds(calendar, ts, param_name)
    320 
    321     return ts

DateOutOfBounds: Parameter `dt` receieved as '2022-01-01 00:00:00+00:00' although cannot be later than the last session of calendar 'XSES' ('2021-12-31 00:00:00+00:00').

**Comment by maread99** [comment]
@npezolano, 2022 holidays for XSES were added in #123, included in release [3.5](https://github.com/gerrymanoim/exchange_calendars/releases/tag/3.5).

I suspect you're using an older version of `exchange_calendars`. Just update it and you should have holidays for 2022.
