### ISSUE TITLE
XIDX calendar

### ISSUE THREAD

**Issue by 0x0L** [gerrymanoim/exchange_calendars#158]
Hello,

The XIDX calendar does not seem to follow the information available at
https://www.idx.co.id/en-us/investhub/trading-hours/

Closing time is wrong and we're also missing the lunch break.

**Comment by gerrymanoim** [comment]
https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc

**Comment by 0x0L** [comment]
Why close the issue ? Is there no issue ?
