### ISSUE TITLE
I found XTAI market holiday date 2022-02-04 is different from TWSE announced schedule.

### ISSUE THREAD

**Issue by pillbox1989** [gerrymanoim/exchange_calendars#164]
According to [TWSE](https://www.twse.com.tw/en/holidaySchedule/holidaySchedule) website, the date 2022-02-04 is holiday, but I use function is_session() it returns True.

`import exchange_calendars as ec`
`xtai = ec.get_calendar('XTAI')`
`print(xtai.is_session("2022-02-04"))`

How to set 2022-02-04 as holiday by function or there is another way to correct this problem?

Thank you!

**Comment by gerrymanoim** [comment]
https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc
