### ISSUE TITLE
Use a timezone-aware object instead.

### ISSUE THREAD

**Issue by mrkgoh** [gerrymanoim/exchange_calendars#20]
Hi I received the following error:

`volume1/homes/admin/Drive/stock/order/stock_buyer.py:58: FutureWarning: Indexing a timezone-aware DatetimeIndex with a timezone-naive datetime is deprecated and will raise KeyError in a future version.  Use a timezone-aware object instead.
  if ecals.get_calendar("XKLS").is_session(pd.Timestamp(date.today().strftime('%Y-%m-%d'))):`

date.today() refers to the local date. Local date is 'Asia/Kuala_lumpur'. Should I do the following instead? 
`if ecals.get_calendar("XKLS").is_session(pd.Timestamp(date.today().strftime('%Y-%m-%d'), tz='Asia/Kuala_lumpur')):`

but if I do that the result is False when it should be True.

**Comment by mrkgoh** [comment]
or should I always default to UTC hence 
`if ecals.get_calendar("XKLS").is_session(pd.Timestamp(date.today().strftime('%Y-%m-%d'), tz='UTC')):`

**Comment by gerrymanoim** [comment]
Generally everything in `exchange_calendar` works with/expects `UTC` times. (I guess we should add a check somewhere). This occurs mostly via https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/utils/pandas_utils.py#L6

If you have localized times you should convert them before checking is_session.
