### ISSUE TITLE
Missing two holidays in XSHG: 2022 Oct 6, Oct 7

### ISSUE THREAD

**Issue by oraix** [gerrymanoim/exchange_calendars#225]
According the information in [sse.com.cn](http://english.sse.com.cn/start/trading/schedule/)
the file [exchange_calendar_xshg](https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/exchange_calendar_xshg.py) is missing two holidays.

**Comment by maread99** [comment]
Thanks for raising this @oraix.

All calendars are user-maintained, please see this [FAQ](https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc) for a link to the process to update calendar holidays.

I'll leave this issue up until a PR comes in (be that from you or someone else interested in this calendar).

**Comment by maread99** [comment]
Closed by #228
