### ISSUE TITLE
Add 19 September 2022 as XLON ad-hoc holiday.

### ISSUE THREAD

**Issue by jenskeiner** [gerrymanoim/exchange_calendars#229]
As announced [here](https://www.gov.uk/government/news/bank-holiday-announced-for-her-majesty-queen-elizabeth-iis-state-funeral-on-monday-19-september), 19 September 2022 will be a UK  bank holiday for Queen Elisabeth II‘s state funeral. So, an ad-hoc holiday should be added accordingly for XLON.

**Comment by maread99** [comment]
Closed by #230
