### ISSUE TITLE
Split out the precomputed holidays as configs

### ISSUE THREAD

**Issue by wulahaier** [gerrymanoim/exchange_calendars#231]
We have a few libraries which depend on exchange_calendars. It is tedious to update all dependencies if we find some holidays missing.

Is it possible to read the precomputed holidays from some configs?

For example, we could read the holidays from `~/.config/exchange_calendars/<exchange_name>_holidays.csv` if it exists,  otherwise use the holidays hardcoded in the code.

**Comment by maread99** [comment]
Hi @wulahaier, please offer a PR if you find missing holidays for any calendar (see [this FAQ](https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc)).

Would that solve the issue?

**Comment by wulahaier** [comment]
> Hi @wulahaier, please offer a PR if you find missing holidays for any calendar (see [this FAQ](https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc)).
> 
> Would that solve the issue?

I made a PR in the past. 
However I  found it not very practical in a production environment. 
Every time we found missing holidays, we need to bump the versions of all applications which depend on exchange calendars and then redeploy all of the applications.

**Comment by maread99** [comment]
Hi @wulahaier.

Holidays by nature are always changing, be they adhoc or 'regular' ones.

A main purpose of `exchange-calendars` is to support a community where users' contributions provide for making a global range of up-to-date calendars available that no single user could reasonably maintain on their own.

If you feel you need to go with the config route I think your best bet would be a local hack.

Cheers.

**Comment by gerrymanoim** [comment]
You're probably better off using some script to generate static holidays from this repository and using those in your production env, if the bump/release/redeploy is difficult in your current environment.
