### ISSUE TITLE
[DOC] Add FAQ Note about default_end time

### ISSUE THREAD

**Issue by gerrymanoim** [gerrymanoim/exchange_calendars#24]
See https://github.com/gerrymanoim/exchange_calendars/issues/21 amd https://github.com/gerrymanoim/exchange_calendars/issues/14. 

Should also port over https://github.com/quantopian/trading_calendars/pull/176/files someday.

**Comment by maread99** [comment]
@gerrymanoim, this issue can probably be closed following merging of #54.

Similarly, could probably delete the pass-kwargs-to-calendar-init branch.
