### ISSUE TITLE
Suggestion: use 'holidays' module to manage holiday dates

### ISSUE THREAD

**Issue by ValueRaider** [gerrymanoim/exchange_calendars#242]
'holidays' module is simple and self-descriptive so I won't elaborate: https://github.com/dr-prodigy/python-holidays

Main reason I suggest it is to avoid duplicating work, and also that module gets new holidays merged in faster than this repo. Eg. the new QEII holiday got merged into their Aussie calendar 4 days faster, and New Zealand Matariki day 1 year faster.

**Comment by maread99** [comment]
Seems like a great resource, although I would be very wary of assuming that a country or region's holidays exactly match the days that local exchanges are closed. In my experience they very often are not the same.

Having said that, perhaps it would be useful to have a script that identifies differences between holidays from https://github.com/dr-prodigy/python-holidays with the holidays defined for an `ExchangeCalendar`. Anyone interested in a particular calendar could use it to identify potential errors to be investigated.

**Comment by ValueRaider** [comment]
They do cover financial holidays - `holidays.financial_holidays('<exchange>)` - but I assumed this was comprehensive. Actually it only provides NYSE.

But the big problem I discover is they don't use pandas, so this would probably kill fabrication performance. So best to limit to testing/debugging as you suggest.

I'll close issue
