### ISSUE TITLE
Is XTAE (Tel Aviv) start time wrong?

### ISSUE THREAD

**Issue by ValueRaider** [gerrymanoim/exchange_calendars#246]
Is XTAE (Tel Aviv) start time wrong? Simple fix but I wanted to allow discussion first.

~[Official start time](https://info.tase.co.il/Eng/about_tase/corporate/Pages/2022.aspx)~ [Official start time](https://info.tase.co.il/eng/trading/trading_schedule/Pages/trading_schedule.aspx) is randomly between 9:59 and 10:00 ; end time randomly between 17:14 and 17.15. The [last change to trading times acknowledges this](https://github.com/gerrymanoim/exchange_calendars/commit/e4b9df8692074300876a17f80f02633b6ffeff5c#diff-010387b34ad4fb89a233a0c2825325b680bc93f1165f6aa9092f09e404bba9f3), but decision process for which times are chosen not consistent. I'd expect either 9:59->17:15 or 10->17.14 to be chosen (ideally the wider range), but instead a hybrid is used: 10->17:15

Any reason why I shouldn't change the start time to 9:59?

**Comment by maread99** [comment]
Haven't come across an exchange that does this before.

Thinking in terms of trading minutes, if during regular trading a trade can be placed between 09:59 and 10.00 then this minute should be represented, same for 17:14 to 17.15.

So I agree with @ValueRaider, 09:59 -> 17.15.

**Comment by gerrymanoim** [comment]
Yep - agreed here, thanks for catching that.

**Comment by maread99** [comment]
Fixed in #247.
