### ISSUE TITLE
Add test here to cover the changes to `scheduled_special_times`

### ISSUE THREAD

**Issue by gerrymanoim** [gerrymanoim/exchange_calendars#252]
- [x] Add test here to cover the changes to `scheduled_special_times`
- [ ] Also add coveragepy and github action to at least alert in coverage drops. 

_Originally posted by @maread99 in https://github.com/gerrymanoim/exchange_calendars/issues/247#issuecomment-1284633890_

**Comment by maread99** [comment]
Alll covered in #254 except adding coveragepy (moved to new issue #257)
