### ISSUE TITLE
Big gaps in SSE calendar

### ISSUE THREAD

**Issue by vilnik** [gerrymanoim/exchange_calendars#288]
The SSE calendar has big and frequent gaps, for instance between 2021-02-10 and 2021-02-18.

**Comment by codeterm** [comment]
> The SSE calendar has big and frequent gaps, for instance between 2021-02-10 and 2021-02-18. No one should use this calendar until this issue has been fixed.

These are Lunar New Year holidays

**Comment by vilnik** [comment]
Okay, thanks! I thought this was the Swedish Stock Exchange, but apparently it is the Shanghai Stock Exchange, my misstake :)
