### ISSUE TITLE
[Bug] Function `previous_close()` returns different results for timezone-naive and timezone-aware datetime objects

### ISSUE THREAD

**Issue by xareelee** [gerrymanoim/exchange_calendars#301]
The market is opening now. I try to get the previous market date by `previous_close()`, but it returns today's close time.

I found that `previous_close()` returns different results for timezone-naive and timezone-aware datetime objects, although they have the same timestamp.

```py
import exchange_calendars as xcals
import datetime

nyse = xcals.get_calendar('NYSE')

now = datetime.datetime.now()
now_utc = datetime.datetime.now(datetime.timezone.utc)
pre_close_time = nyse.previous_close(now)
pre_close_time_utc = nyse.previous_close(now_utc)

print(now)      # naive timezone (my timezone is UTC+8)
print(now_utc)  # aware timezone
print(now.timestamp())      # (almost) same timestamp
print(now_utc.timestamp())  # (almost) same timestamp
print(pre_close_time)       # different results
print(pre_close_time_utc)   # different results
```

Results:

```
2023-04-11 02:13:09.336598
2023-04-10 18:13:09.336616+00:00
1681150389.336598
1681150389.336616
2023-04-10 20:00:00+00:00
2023-04-06 20:00:00+00:00
```

Please support timezonoe-naive datetime objects, so I cat simply get the previous close time without making a timezone-aware datetime object:

```py
pre_close_time = nyse.previous_close(datetime.datetime.now())
#=> expect: 2023-04-06 20:00:00+00:00
#=> now I get: 2023-04-10 20:00:00+00:00
```

**Comment by maread99** [comment]
Hi @xareelee

You seem to be suggesting that a tz-naive timestamp should be considered to have the same timezone as the user's system as opposed to UTC?

This would be very confusing given that the times being queried are in UTC.

**Comment by xareelee** [comment]
Hi @maread99 

I got it. I found that the `ExchangeCalendar` has a property `tz` for that:

```py
print(datetime.datetime.now())                          # my timezone (naive)
print(datetime.datetime.now(datetime.timezone.utc))     # UTC+0 (aware)
print(datetime.datetime.now(nyse.tz))                   # NYSE timezone (aware)  <- that's what I need
```

It fixes my problem.

**Comment by maread99** [comment]
For your case of wanting to pass 'now' to `previous_close`  it doesn't matter what timezone you pass to the `now` function - they will all represent the same time (i.e. 'now').

What you can't do is pass `previous_close` (or any other method) a tz-naive timestamp and expect it to be interpreted in any way other than UTC.
