### ISSUE TITLE
There are wrong date outcomes for Turkey 

### ISSUE THREAD

**Issue by emrahyalcin23** [gerrymanoim/exchange_calendars#303]
I don't the library provides only the scheduled holidays or the opened dates, so my issue might not be one. If it gives opened dates, then, after the earthquake, the market were closed for almost a week. So, 2023-02-09 / 2023-02-14 shouldn't be existed.

**Comment by maread99** [comment]
Hi @emrahyalcin23.

The calendars reflect times / sessions when the market was open. Unscheduled changes should are included to the `adhoc_holidays` property.

I think you'll find the dates you mention have already been added and were included in [release 4.2.6](https://github.com/gerrymanoim/exchange_calendars/releases/tag/4.2.6). Perhaps you just need to upgrade to the latest version?

**Comment by maread99** [comment]
Closing as believe these changes were made in release 4.2.6.

@emrahyalcin23, let us know if you don't think this is the case and I'll reopen it.
