### ISSUE TITLE
XKLS 2023 calendar not updated 

### ISSUE THREAD

**Issue by tys203831** [gerrymanoim/exchange_calendars#305]
Bursa Malaysia's trading calendar is not updated yet: https://publicholidays.com.my/2023-dates/.

**Comment by tys203831** [comment]
@gerrymanoim 

This is a question on XKLS calendar

I see, just for Feb 5, it's originally a Thaipusam holiday on Sunday, however for **Bursa Malaysia**, if a public holiday falls on Sunday, the following day shall be a public holiday, and if this day is already a holiday, then the next day shall be a public holiday.

Is there any automatic code to represent it?

![image](https://user-images.githubusercontent.com/64836390/233535337-f97b9f70-21d8-43fc-9f02-46b981fb3275.png)

**Comment by tys203831** [comment]
Here are the dates need to be changed and updated:

24 Apr 2023
28 June need to change to 29 June
27 Sep need to change to 28 Sep
12 Nov (deepavali) -> 13 Nov

will look into more on how to contribute this calendar

**Comment by gerrymanoim** [comment]
Thanks for the PR! If the CI passes we'll merge.

**Comment by maread99** [comment]
Closed by #306
