### ISSUE TITLE
ENH: expose get_calenadar kwargs including "side" option

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#31]
@gerrymanoim, would you entertain a PR that introduces a `side` parameter to `get_calendar` to determine the minutes when a calendar should be considered open? Options would be as follows with default as "both" such that existing behaviour would remain unchanged:
* **"left"** - treat session open and break_start as open, treat session close and break_end as closed.
* **"right"** - treat session open and  break_start as closed, treat session close and break_end as open.
* **"both"** - treat all of session open, session close, break_start and break_end as open.
* **"neither"** - treat none of session open, session close, break_start or break_end as open.

I feel this would give the user useful flexibility.

I've employed a hack to implement the above on something I'm working on. The implementation's fairly simple (it would also be possible to add a `side` option to methods such as `minutes_in_range` and `minute_to_session_label` to override the global `side` value for any particular call).

I'd happily offer a PR if you think a `side` option would be a worthy enhancement?

I notice that you previously got together a PR to expose the `get_calendar` `start` and `end` parameters (as referenced from #24). I could introduce this at the same time.

With regards to the **cache**, occurs to me to either:
* ditch it
* keep it but only retrieve from it if kwargs match those of the cached version, otherwise overwrite the cached version with a new calendar instance.

Thoughts?

**Comment by gerrymanoim** [comment]
Interesting. Originally the way exchange calendars worked was to have the first minute be treated as closed, which got changed here: https://github.com/gerrymanoim/exchange_calendars/pull/3/files and required threading that change through in a bunch of places. I don't think I have any functional issue with allowing the flexibility you're proposing, but I worry it will make testing these configurations difficult for a feature that might not have that broad of a use case (vs just having the user handle it in their own context). But I could be wrong! 

`get_calendar` taking start and end params would be a great addition. I'm not really tied to having a cache anymore (calendar construction is reasonably fast and users that do have specific performance requirements can probably handle their own caching as well).

**Comment by maread99** [comment]
Thanks for the comments. I used to have an ugly module sit on top of trading_calendars to get opens/closes and minutes in the terms I was after. I've since overhauled it for exchange_calendars. I require, in most cases, for minutes to be defined on 'left' which I personally find most logical, although understand different users have different purposes. I've ended up subclassing the dispatcher to override the get_calendar method and then use types.new_class to override the affected ExchangeCalendar methods. Whilst the workaround is pretty complicated the acutal implementation is simple enough. More than once I've found myself saying 'the place for this is in exchange_calendars'.

I had similar thoughts to you regarding testing. I'm thinking I'll work on a PR, see where I get to and push it to see what you reckon(?).

With regards to the `start` / `end` parameters, I've probed the bounds of each calendar and seen that there are three main causes of dates being out-of-bounds:
* A few calendars explicitly raise errors if the user tries to create a calendar outside of the dates for which the calendar is considered valid (for example, XBOM, XSHG).
* Some calendars fail as a result of conflicts between rules, ususally when evaluting special dates (for example XNYS, XKLS).
* Most calendars are only restricted by Timestamp.min and Timestamp.max, i.e. you could create calendars for exchanges before the exchange existed.

Having given this some thought, I wonder if the best approach would be to:
1) define an abstract base implementation for ExchangeCalendar subclasses to raise out-of-bounds errors.
2) for those calendars without defined bounds:
    * define default start / end dates within which calendars are considered likely to be reliable. @gerrymanoim, I guess these dates would be the current defaults? Would you have any knowledge of the date range over which quantopian intended the calendars to be accurate?
    * include a `allow_uncharted_waters` parameter to let users create calendars outside of these default limits only if they explictly acknowledge what they are asking for.

**Comment by gerrymanoim** [comment]
> I had similar thoughts to you regarding testing. I'm thinking I'll work on a PR, see where I get to and offer it to see what you reckon(?).

Yeah - that sounds good to me. If it isn't painful to test all iterations here, I'm open to providing the flexibility. 

>  I guess these dates would be the current defaults? Would you have any knowledge of the date range over which quantopian intended the calendars to be accurate?

I'd also guess that the defaults provide "safe" dates. IIRC quantopian had data going back to `2002-01-03` in the US - not sure about what the coverage was in other countries. My guess is these were mostly chosen arbitrarily: https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/exchange_calendar.py#L37-L41.

**Comment by gerrymanoim** [comment]
XBOM/XSHG look like they're raising because of https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/precomputed_exchange_calendar.py

Given that - I don't think we need to make it more complicated than the interface in https://github.com/quantopian/trading_calendars/pull/176/files. If you choose dates that break a precomputed calendar, that's a valid `ValueError` that we raise. Otherwise you're generally using this at your own risk (as is the case now when you accept the arbitrary start/end dates). Thoughts?

**Comment by maread99** [comment]
> Given that - I don't think we need to make it more complicated than the interface in https://github.com/quantopian/trading_calendars/pull/176/files. If you choose dates that break a precomputed calendar, that's a valid ValueError that we raise. Otherwise you're generally using this at your own risk (as is the case now when you accept the arbitrary start/end dates). Thoughts?

Happy to keep it simple! I'll flesh out the documentation.

**Comment by maread99** [comment]
`side` option implemented in #71.
