### ISSUE TITLE
ASX closes early on two days in the year at 2:10pm

### ISSUE THREAD

**Issue by j7zAhU** [gerrymanoim/exchange_calendars#319]
ASX closes early two days in the year (Last day before Christmas and Last day of year) at 2:10pm

https://www.marketindex.com.au/trading-hours

**Comment by gerrymanoim** [comment]
https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc
