### ISSUE TITLE
Drop `pytz` in favor of `zoneinfo` standard library

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#322]
`zoneinfo` ([ref](https://docs.python.org/3/library/zoneinfo.html)) was added to the standard library in Python 3.9 and can now replace the third-party `pytz`.

Pandas currently supports both `pytz` and `zoneinfo`. It continues to mostly use `pytz` by default, however, [it would appear](https://github.com/pandas-dev/pandas/issues/34916) that Pandas' intention is very much to change to using `zoneinfo` by default, and possibly to drop `pytz` altogether. It was originally suggested that they would move to `zoneinfo` in Pandas 2.0 ([ref](https://github.com/pandas-dev/pandas/issues/44823)) although this didn't happen and it seems that the actual path is yet to be decided.

More widely it seems there's a general movement in Python from `pytz` to `zoneinfo`. The Pandas' [issue](https://github.com/pandas-dev/pandas/issues/34916) notes that Django has dropped `pytz` and also that `pytz` can be inaccurate from 2038. It all suggests it's probably only a matter of time until `exchange-calendars` needs to make the move.

The earliest that the change could happen would be on advancing the minimum supported Python version to 3.9, which I was hoping to do in the near future. I'm happy to make the changes now and get it done. It would be breaking for any clients who are directly operating on a timezone instance (the `pytz` timezone interface differs from that of `zoneinfo`). I'd be surprised if such usage is common. We could release as a new minor version 4.3 that advances the minimum supported Python version to 3.9 and moves from `pytz` to `zoneinfo`.

Aside from having to (probably) do this eventually, an advantage of moving over is simply to lose a third-party dependency. Relying on `zoneinfo` does require the `tzdata` dependency for the Windows OS, although this is a first-party dependency, and at any rate it's a dependency of Pandas.

@gerrymanoim, what do you reckon, shall I move to `zoneinfo` as part of a release that also advances the minimum supported version to 3.9? (btw, we need to advance the minimum version to 3.9 to support numpy >= 1.25)

**Comment by gerrymanoim** [comment]
Yep - fully agree - let's move to zoneinfo if possible.

**Comment by ValueRaider** [comment]
Some thoughts on versioning ...

---

> It would be breaking for any clients who are directly operating on a timezone instance

Breaking codes warrants increasing major version not minor.

I'm sceptical that `exchange_calendars` use cases are affected by 2038 problem, so no reason to force users to switch in order to get other bug fixes / calendar updates. Meaning, backport fixes for a while so users have time to migrate away from `pytz`.

Finally, I can beta-test, I have a data pipeline that largely uses `ZoneInfo` already.

**Comment by maread99** [comment]
Hi @ValueRaider, thanks for the input.

> I'm sceptical that exchange_calendars use cases are affected by 2038 problem  

Yeah, they probably aren't. It's more about dropping a third-party library that pandas are moving away from. I'd rather make the change now when I've got time available than find pandas drop it a few months down the road when I haven't.

I wouldn't have thought the change would have much effect downstream. The only situations that occur to me where it could require clients implementing changes would be if they are:
* operating directly on the timezone object (a rare use case, no?)
* asserting an instance is a timezone (probably not overly common, and a simple fix)
* including a timezone in `if` statements, for example `if tz==pytz.UTC:`. This seems a more likely case, but again the fix is simple.

I agree the ideal would be to backport fixes on a separate branch. I'm not sure it's practical though given the realities of maintaining FOSS packages. This week I can find time to push the change through but I won't subsequently have time to maintain a separate branch.

### **If anyone out there foresees that `exchange_calendars` moving from `pytz` to `zoneinfo` is going to cause them problems then PLEASE do speak now and I'll hold off**.

Cheers

**Comment by kmcminn** [comment]
+1 for NOT using zoneinfo.

countries are changing timezones (adding/removing seconds, tweaking DST, etc) on an ongoing basis and each one of these requires code/data SOMEWHERE to handle every outlier. For that reason to find the accurate time in the past requires essentially a maintained database of these time rules. zoneinfo does not provide this, and even if it did, the cadence would be too slow to get updates (people don't upgrade python versions in codebases often).

**Comment by maread99** [comment]
Thanks for the comment @kmcminn.

My understanding is that neither `pytz` or `zoneinfo` maintain a database, rather both refer to the [IANA time zone database](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority). `zoneinfo` does this via the OS where it can, or otherwise (e.g. for Windows) via the first-party `tzdata` dependency. Accordingly with `zoneinfo` the data should be the same and updates may be quicker than `pytz` (if able to access via the OS) or the same (if relying on updating the `tzdata` dependency).

Indeed, the README for the latest `pytz` release states...
> Projects using Python 3.9 or later should be using the support now included as part of the standard library, and third party packages work with it such as [tzdata](https://pypi.org/project/tzdata/). pytz offers no advantages beyond backwards compatibility with code written for earlier versions of Python.

**Comment by gerrymanoim** [comment]
My understanding is the same as @maread99 - but please correct me if I'm wrong. My thinking is mostly around reducing our dependency burden and doing the more "standard" thing now that python has done a better job standardizing this via https://docs.python.org/3/library/zoneinfo.html / https://peps.python.org/pep-0615/.

**Comment by kmcminn** [comment]
the tzdata/time dependency doesnt really change much whether using zoneinfo or pytz, it just moves it

i want to move to zoneinfo but when I went to their test cases and didn't see any good ambiguous time test cases :/

the embeded iana db in pytz was always a nice feature for tzdata consistency. while they didnt have much test coverage they did cover dst and ambiguous times which is what i always worry about with time. also pd.TimeStamp implements this but I havne't explored it

as a consumer of exchange_calendars and forks I'm just interested in time accuracy

thanks for the discussion

**Comment by gerrymanoim** [comment]
> the tzdata/time dependency doesnt really change much whether using zoneinfo or pytz, it just moves it

to clarify - it moves it to the standard library (which we will always have access to) vs an external package.

**Comment by maread99** [comment]
Just released [exchange-calendars 4.3](https://github.com/gerrymanoim/exchange_calendars/releases/tag/4.3). **4.3 continues to use `pytz`.**

It's anticipated that the migration from `pytz` to `zoneinfo` will happen in 4.4 and that this will be released later this week (by 24/09/08).

4.3 includes fixes for the latest pandas version 3.1 (#327). 4.3 has been released ahead of migrating to `zoneinfo` in order to provide for an up-to-date stable version that users can pin to whilst making any changes that they may require to accommodate `zoneinfo` in 4.4.

**Comment by maread99** [comment]
Version [4.5](https://github.com/gerrymanoim/exchange_calendars/releases/tag/4.5) makes the move from `pytz` to `zoneinfo` (there is no version 4.4).
