### ISSUE TITLE
new holiday in KRX 2023

### ISSUE THREAD

**Issue by TaehyunJo-CP** [gerrymanoim/exchange_calendars#335]
As October 2, 2023 was designated as a temporary public holiday, the stock market will be closed.

https://global.krx.co.kr/contents/GLB/05/0501/0501110000/GLB0501110000.jsp

It seems exchange_calendars doesn't update this new holiday.

**Comment by gerrymanoim** [comment]
https://github.com/gerrymanoim/exchange_calendars#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc

**Comment by maread99** [comment]
Closed by #336
