### ISSUE TITLE
open time in exchange_calendar_xkrx.py

### ISSUE THREAD

**Issue by nballen-tx** [gerrymanoim/exchange_calendars#337]
Hi,

the open time is specified as following in code row #41-42

Open Time: 9:00 AM, KST (Korean Standard Time)
Close Time: 3:30 PM, KST (Korean Standard Time)

however the code has 

    open_times = (
        (None, time(9, 30)),
        (pd.Timestamp("1978-04-01"), time(10, 0)),
        (pd.Timestamp("1986-04-01"), time(9, 40)),
        (pd.Timestamp("1995-01-01"), time(9, 30)),
        (pd.Timestamp("1998-12-07"), time(9, 0)),
    )

Looks like a typo.

Thanks,

**Comment by maread99** [comment]
@nballen-tx, thanks for the comment.

The code is saying that the usual opening time was 09:30 until "1978-04-01" from when it was 10:00 until "1986-04-01" from when it was 09:40, etc.

Since "1998-12-07" the usual open time has been 09:00, hence this being the time stated in the doc.
