### ISSUE TITLE
`is_session` call failing for XBOM exchange calendar

### ISSUE THREAD

**Issue by ajmeraayam** [gerrymanoim/exchange_calendars#347]
When calling `is_session` method with any date in 2024, it returns an error as shown below

>>> bse.is_session(datetime(2024, 1, 1, 0, 0, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "_location_\exchange_calendar.py", line 1250, in is_session
    date = parse_date(date, "date", self)
  File "_location_\exchange_calendars\calendar_helpers.py", line 393, in parse_date
    raise errors.DateOutOfBounds(calendar, ts, param_name)
exchange_calendars.errors.DateOutOfBounds: Parameter `date` receieved as '2024-01-01 00:00:00' although cannot be later than the last session of calendar 'XBOM' ('2023-12-29 00:00:00')

I can see the holidays for 2024 are updated but the schedule isn't being updated for the year 2024. The schedule ends on 29th December 2023 since the 30th and 31st are weekends.

**Comment by maread99** [comment]
Hi @ajmeraayam. The XBOM holidays for 2024 were updated subsequent to the most recent release. They'll show up in the next release. In the meantime you could install directly against the master, something like the following should work...
```
$ pip install git+https://github.com/gerrymanoim/exchange_calendars.git#egg=exchange_calendars
```

**Comment by ajmeraayam** [comment]
Thanks @maread99. Works like a charm. I am going to close the issue as resolved.
