### ISSUE TITLE
XCSE - Prayers day is now not a holiday in Denmark

### ISSUE THREAD

**Issue by markhorup** [gerrymanoim/exchange_calendars#363]
From 2024 the politicians has decided that Prayers day (26th of April in 2024) is not a holiday.

**Comment by maread99** [comment]
Thanks @markhorup.

All calendar updates are user-contributed. Workflow for a PR to **modify an existing Exchange Calendar** is [here](https://github.com/gerrymanoim/exchange_calendars/blob/master/.github/pull_request_template.md).
