### ISSUE TITLE
XKRX - 2024 Election Day missing in calendar

### ISSUE THREAD

**Issue by GCM-Karl** [gerrymanoim/exchange_calendars#366]
Although the Election Day on April 10, 2024 is not an official holiday, both the Bank of Korea and the Korean Stock Exchange will remain closed. In the XKRX calendar, however, the day is marked as Open.

**Comment by herebebeasties** [comment]
The [official page for the National Election Commission](https://www.nec.go.kr/site/eng/02/10203000000002020070611.jsp) still has this down as provisional and the [KRX official market holiday page](https://global.krx.co.kr/contents/GLB/05/0501/0501110000/GLB0501110000.jsp) does not currently list this, although it seems likely that the date will be confirmed shortly (typically seems to be 50-60 days beforehand for past ones).

What's the stance on including provisional future dates like this? Do we wait until they have been officially confirmed?
