### ISSUE TITLE
Add EEX holiday calendar for futures

### ISSUE THREAD

**Issue by ksenia1997** [gerrymanoim/exchange_calendars#381]
I am requesting the addition of the EEX (European Energy Exchange) holiday calendar for futures to the exchange_calendars project. 

The EEX holiday calendar provides important information regarding trading holidays and non-trading days specific to EEX futures, and its inclusion would greatly benefit users who rely on this calendar for trading and scheduling purposes.

**Details:**
-  **Calendar Source:** [Link to the EEX holiday calendar PDF](https://www.eex.com/fileadmin/EEX/Downloads/Trading/Calendar/Holiday_Calendar/20230303_Trading_Calendar_EEX_Group.pdf)
- **Importance:** EEX is a significant exchange for energy futures trading in Europe, and having its holiday calendar available in exchange_calendars would enhance the utility of the project for users in the energy trading domain.

Thank you for considering this request.

**Comment by maread99** [comment]
Added by #385 / #386.

Thanks for raising this @ksenia1997, and thanks to @romanzdk for implementing.
