### ISSUE TITLE
ModuleNotFoundError: No module named 'exchange_calendars'

### ISSUE THREAD

**Issue by StepanSushko** [gerrymanoim/exchange_calendars#391]
I install 'exchange_calendars' using 'pip install exchange_calendars' version 4.5.4 in Python 3.10.4. Installing process is successful, but when I try to import, I get "ModuleNotFoundError: No module named 'exchange_calendars'".

**Comment by maread99** [comment]
Hi @StepanSushko. I'm not getting this error with 4.5.4. Could it be an issue with your environment? Could you confirm that you've installed the package to the same environment that you're executing the code in. Thanks.
