### ISSUE TITLE
XNSE and XBOM holiday 2024-05-20

### ISSUE THREAD

**Issue by npezolano** [gerrymanoim/exchange_calendars#395]
2024-05-20 was election day in Indian and both XBOM and XNSE were closed

https://www.nseindia.com/resources/exchange-communication-holidays
https://www.bseindia.com/static/markets/marketinfo/listholi.aspx

**Comment by magic-man** [comment]
This would be great to have corrected to not have to manually correct for this.

**Comment by maread99** [comment]
Fixed by #390
