### ISSUE TITLE
Getting AttributeError: 'NoneType' object has no attribute 'total_seconds' requesting calendar for XNYS

### ISSUE THREAD

**Issue by chadale** [gerrymanoim/exchange_calendars#397]
following code (jupyterhub notebook):

import pandas as pd
import numpy as np
from datetime import datetime, date, timedelta
import exchange_calendars as xcals
xnys = xcals.get_calendar('XNYS')

Get following error: AttributeError: 'NoneType' object has no attribute 'total_seconds' 

Full trace in file attached.

[CalendarErrors.txt](https://github.com/user-attachments/files/15916649/CalendarErrors.txt)

**Comment by maread99** [comment]
Hi @chadale, I'm unable to replicate this error. If you're not already using the latest version of `exchange_calendars`(?) could you try upgrading and see if that fixes it. If that doesn't work then I'd suggest upgrading the dependencies to the latest versions. Let us know if none of that does the trick.
