### ISSUE TITLE
us_extended_hours not available in default install

### ISSUE THREAD

**Issue by quantmode** [gerrymanoim/exchange_calendars#411]
The us_extended_hours calendar is not available in the standard install generated by `pip install exchange_calendars`. It's missing from exchange_calendars/calendar_utils.py, although it is present in the latest version in the repository.

**Comment by maread99** [comment]
Hi @quantmode.

I'm having trouble finding the us_extended_hours calendar you refer to. Could you provide a link to the file please. Thanks.

**Comment by quantmode** [comment]
My apologies, this comment was meant for the quantrocket fork of exchange_calendars. There you'll see there is a US extended hours calendar referenced in. https://github.com/quantrocket-llc/exchange_calendars/blob/master/exchange_calendars/calendar_utils.py
