### ISSUE TITLE
Taiwan (XTAI) missing trading day 2024-09-16

### ISSUE THREAD

**Issue by dinohsu1019** [gerrymanoim/exchange_calendars#413]
Taiwan calendar (XTAI) should be updated, since 2024-09-16 is a trading day, version 4.5.6, thanks.

Code:
import pandas as pd
import exchange_calendars as xcals
xtai = xcals.get_calendar("XTAI") # Taiwan stock exchange
all_xtai_trade_dates = list(xtai.schedule.index.values)
print(xcals.__version__)
list(filter(lambda x: pd.Timestamp('2024-09-01') <= x <= pd.Timestamp('2024-09-30'), all_xtai_trade_dates))

Output:
4.5.6
[numpy.datetime64('2024-09-02T00:00:00.000000000'),
 numpy.datetime64('2024-09-03T00:00:00.000000000'),
 numpy.datetime64('2024-09-04T00:00:00.000000000'),
 numpy.datetime64('2024-09-05T00:00:00.000000000'),
 numpy.datetime64('2024-09-06T00:00:00.000000000'),
 numpy.datetime64('2024-09-09T00:00:00.000000000'),
 numpy.datetime64('2024-09-10T00:00:00.000000000'),
 numpy.datetime64('2024-09-11T00:00:00.000000000'),
 numpy.datetime64('2024-09-12T00:00:00.000000000'),
 numpy.datetime64('2024-09-13T00:00:00.000000000'),
 numpy.datetime64('2024-09-18T00:00:00.000000000'),
 numpy.datetime64('2024-09-19T00:00:00.000000000'),
 numpy.datetime64('2024-09-20T00:00:00.000000000'),
 numpy.datetime64('2024-09-23T00:00:00.000000000'),
 numpy.datetime64('2024-09-24T00:00:00.000000000'),
 numpy.datetime64('2024-09-25T00:00:00.000000000'),
 numpy.datetime64('2024-09-26T00:00:00.000000000'),
 numpy.datetime64('2024-09-27T00:00:00.000000000'),
 numpy.datetime64('2024-09-30T00:00:00.000000000')]

**Comment by mcazim98** [comment]
Faced this same issue. I think it has to do with the Mid autumn timings for Taiwan.

**Comment by gerrymanoim** [comment]
https://github.com/gerrymanoim/exchange_calendars?tab=readme-ov-file#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc

Feel free to open a PR to fix.

**Comment by maread99** [comment]
Would be fixed by #413
