### ISSUE TITLE
Japan Exchange showing trading day instead of holiday for Autumnal Equinox 

### ISSUE THREAD

**Issue by mcazim98** [gerrymanoim/exchange_calendars#418]
**Source: Tokyo Stock Exchange**
![image](https://github.com/user-attachments/assets/55c480ac-e675-4a27-af57-4d7ffd694fad)

The holiday for Autumnal Equinox is not showing up in exchange calendar for Exchange: XTKS.

Python version: 3.10.8
Exchange Calendar versions: 4.5.6

**Comment by maread99** [comment]
Thanks for raising this @mcazim98.

All calendar updates are user-contributed, please see [this](https://github.com/gerrymanoim/exchange_calendars?tab=readme-ov-file#calendar-is-missing-a-holiday-has-a-wrong-time-should-have-a-break-etc) FAQ section of the README.

**Comment by w3stling** [comment]
I am unable to reproduce this.

The holiday for Autumnal Equinox (2024-09-23) was added by PR #342
