### ISSUE TITLE
AttributeError: 'UTC' object has no attribute 'key'

### ISSUE THREAD

**Issue by bbalouki** [gerrymanoim/exchange_calendars#424]
I read a lot about this issue in previous issues, but I still have this error, and this is not an issue with Zipline, it is an issue with exchange-calendar API. Can someone help with this issue?

**Comment by maread99** [comment]
Hi @bbalouki, can you offer a minimal example please.

**Comment by bbalouki** [comment]
@maread99 Here is the example
`from exchange_calendars import get_calendar
from bbstrader.metatrader.rates import Rates
if __name__ == "__main__":
    symbol = 'GBPUSD'
    rates =  Rates(symbol, time_frame='D1',)
    tz = pytz.timezone('UTC')
    start = pd.Timestamp('2010-06-01', tz=tz)
    end = pd.Timestamp('2024-10-04', tz=tz)
    data = rates.get_historical_data(
        date_from=start,
        date_to=end,
        save_csv=True,
    )
    calendar = get_calendar('CME')
    valid_sessions = calendar.sessions_in_range(start, end)
    data = data[data.index.isin(valid_sessions)]
    print(len(data))
    print(data.head())
    print(data.tail())
    print(data.index.tzinfo)
`
Traceback (most recent call last):
  File "C:\Users\Bertin\GitProjects\bbstrader\test.py", line 35, in <module>
    valid_sessions = calendar.sessions_in_range(start, end)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\mt5\Lib\site-packages\exchange_calendars\exchange_calendar.py", line 2204, in sessions_in_range      
    slc = self._get_sessions_slice(start, end, _parse)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\mt5\Lib\site-packages\exchange_calendars\exchange_calendar.py", line 2181, in _get_sessions_slice    
    start, end = self._parse_start_end_dates(start, end, _parse)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\mt5\Lib\site-packages\exchange_calendars\exchange_calendar.py", line 2177, in _parse_start_end_dates 
    return parse_date(start, "start", self), parse_date(end, "end", self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\miniconda3\envs\mt5\Lib\site-packages\exchange_calendars\calendar_helpers.py", line 379, in parse_date
    f"Parameter `{param_name}` received with timezone defined as '{ts.tz.key}'"
                                                                   ^^^^^^^^^
AttributeError: 'UTC' object has no attribute 'key'

**Comment by maread99** [comment]
Hi again.

There seems to be two things going on here.

First off,  `exchange_calendars` stopped supporting `pytz` in version 4.5. This is why you're getting a pretty obscure error message. It now uses the standard library's zoneinfo module. So the 'start' and 'end' above would be defined as:

``` python
from zoneinfo import ZoneInfo
start = pd.Timestamp('2010-06-01', tz=ZoneInfo("UTC"))
end = pd.Timestamp('2024-10-04', tz=ZoneInfo("UTC"))
```

However, this would only give you a more useful error message:
```python
cal.sessions_in_range(start, end)
```
```
ValueError: Parameter `start` received with timezone defined as 'UTC' although a Date must be timezone naive.
```

In short, the `sessions_in_range` parameters 'start' and 'end' take dates, and a date can't have a timezone.

**Comment by bbalouki** [comment]
Thanks @maread99 I think I get it now.
