### ISSUE TITLE
2021-5-4 2021-5-5 is a holiday but not in file 

### ISSUE THREAD

**Issue by rwayan** [gerrymanoim/exchange_calendars#52]
https://github.com/gerrymanoim/exchange_calendars/blob/master/exchange_calendars/exchange_calendar_xshg.py

**Comment by gerrymanoim** [comment]
Please see the FAQ: https://github.com/gerrymanoim/exchange_calendars#why-is-holiday-missing-for-calendar

This was also fixed in https://github.com/gerrymanoim/exchange_calendars/pull/36
