### ISSUE TITLE
ExchangeCalendar._minute_to_session_label_cache - still required?

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#82]
@gerrymanoim, given the break with zipline, is there any reason why we would want to keep the [ExchangeCalendar._minute_to_session_label_cache](https://github.com/gerrymanoim/exchange_calendars/blob/f9853f0e2370f3489945fdf8ad1fae8da09f75ee/exchange_calendars/exchange_calendar.py#L230), or can we lose it?

**Comment by gerrymanoim** [comment]
IIRC it helped in the common use case, but I have no particular attachment to it.

**Comment by maread99** [comment]
Due to remove under PR #71, commit titled "Remove _minute_to_session_label_cache".
