### ISSUE TITLE
Move ExchangeCalendar.exectution_minutes_* methods to QuantopianUSFuturesCalendar ?

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#84]
@gerrymanoim, what do you think about moving the ExchangeCalendar `execution_minutes_for_session` and `execution_minutes_for_sessions_in_range` methods (and the supporting `execution_time_from_open` and `execution_time_from_close`) out of ExchangeCalendar (or at least deprecating them) and into 'QuantopianUSFuturesCalendar'?

These methods seem to have been defined specifically for `QuantopianUSFuturesCalendar` (and indeed for a specific usage case of that calendar) - for all other calendars these methods return the same as the normal `minutes_for_session` and `minutes_for_sessions_in_range` methods. Would it not be clearer (particularly in light of the break with Zipline) to lose this clutter from ExchangeCalendar and have these methods represented only on the QuantopianUSFuturesCalendar?

**Comment by gerrymanoim** [comment]
Yep - that makes sense! Great suggestion.

**Comment by maread99** [comment]
PR #71 commit 'Extend ExchangeCalendarTestBaseProposal, Answers 3' deprecates `execution_*` methods from `ExchangeCalendar` (to be removed with release 4.0 - included to #61) and moves functionality exclusively to `QuantopianUSFuturesCalendar`.
