### ISSUE TITLE
Zipline-Trader incompatibilities

### ISSUE THREAD

**Issue by Sutyke** [gerrymanoim/exchange_calendars#9]
Hi Gerry,

Community continues Zipline development in new fork, I noticed you have started to maintain Q trading_calendars under new name but depreciated some items that are currently used by Zipline. Would you be happy to work together to include also features required by zipline trader or we would need to maintain own trading calendar?

If you are interested please join us at Zipline Trader:
- [Slack](https://zipline-live.slack.com/join/shared_invite/zt-2eswh6cg-RkkAfook7cvREnQfit6qGA#/) 
- [Contribute to GitHub](https://github.com/shlomikushchi/zipline-trader)
- [Check new Docs ](https://zipline-trader.readthedocs.io/en/latest/notebooks/Alphalens.html)
- [Lear from video tutorial ](https://www.youtube.com/watch?v=cTLSCjPFQvY)
- [Read Blog - Linear Regression For a Momentum Based Trading Strategy Using Zipline Trader](https://alpaca.markets/learn/linear-regression-zipline-trader/)

**Comment by gerrymanoim** [comment]
Hey @Sutyke - apologies for missing this issue. In general I'm happy to help with answering questions/reviewing PRs but I don't currently have time to do other development in my free time. 

A lot of the old zipline support was purposely dropped to 

1. Older/deprecated versions of python/pandas/numpy making the code very difficult to use and test
2. Functionality (such as the 1 minute delay in open/close) that only made sense when using this library with zipline.
